name: "TOML Editor V2"
description: "Edit a Table/Key in a given TOML file."
author: "ciii"
branding:
  icon: "file"
  color: "blue"
inputs:
  file:
    description: "The relative path of toml file"
    required: true
  key:
    description: "Key need to modify"
    required: true
  value:
    description: "Value to set"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
